### ISSUE TITLE
Last few seconds content is not playing in offline mode for downloaded video

### ISSUE THREAD

**Issue by qzzzzzzzzzzz** [bitmovin/bitmovin-player-android-samples#49] opened 2019-06-04 09:00 UTC
**Which sample is this report about?**
Sample name or link:
https://github.com/bitmovin/bitmovin-player-android-samples/tree/master/OfflinePlayback
Describe the bug
In the latest SDK version 2.25.0 and 2.25.1, we are facing the problem of downloaded content unable to play in offline in the last few seconds of every content.

Same issue is found in the latest sample code provided and the provided sample stream videos also.

**To Reproduce**
1. Download the content
2. Play downloaded content in offline mode
3. unable to play content in last few seconds it showing a loader

**Expected behavior**
Downloaded content should be played in offline completely.

**Smartphone (please complete the following information):**
 - Device: All Devices
 - OS: Android
 - Version: All

**Additional context**
   The issue is seen in in the latest versions of your android sdk..ie 2.25.0 and 2.25.1.
**The downloaded content play smoothly in previous versions of your sample..ie 2.24.0**

Please check this issue and do the needful changes, Your immediate reply will be highly appreciated.

**Comment by matamegger** [comment] 2019-06-04 09:31
Duplicate of https://github.com/bitmovin/bitmovin-player-android-samples/issues/47

**Closed by matamegger** 2019-06-04 09:31 UTC
