### ISSUE TITLE
Downloading progress showing inconsistently

### ISSUE THREAD

**Issue by Prashantj007** [bitmovin/bitmovin-player-android-samples#57] opened 2019-08-08 10:20 UTC
**Which sample is this report about?**
- Sample name or link: Offline Playback(Version: 2.27.1)

**Describe the bug**
Downloading progress showing inconstancy

**To Reproduce**
1. Tap on download 
2. Downloading starts after a few percents downloading  
3. Once goes back and open downloading screen observe downloading progress it showing less than an actual percent.

For Example, Any content downloading 35% user close the app and relaunch it showing 24%

**Expected behavior**
It should be started from actual progress

**Smartphone (please complete the following information):**
 - Device: SONY
 - OS: ALL
 - Version:ALL

**Comment by matamegger** [comment] 2019-09-11 13:22
Hej, thanks for reaching out.

Are you using the default assets of the sample? How many tracks do you choose to download?
Just for completeness: Do you see this issue as well in the current version of the player (`2.29.0`)?

**Comment by Prashantj007** [comment] 2019-09-14 06:10
Yes.This issue available on 2.29.0 version.
If I download one content with multiple subtitles removes particular content.
When I go to download that content next time it showing inconsistency progress (like direct 67% start onwards)

**Comment by matamegger** [comment] 2019-09-14 08:25
Thanks! We will look into it and keep you updated!

**Comment by matamegger** [comment] 2019-09-16 08:15
@Prashantj007 
Unfortunately we couldn't reproduce this issue with the default assets in the sample.
I would like to ask you to provide us a sample asset you can observe this behaviour.
Further, a more detailed guide on reproducing the issue. In your initial comment, you say closing the app and relaunching, however, if you don't stop/suspend the download before, it would increase due to the background downloading. 
Maybe you are using a restricted network connection as well?

**Comment by Prashantj007** [comment] 2019-09-16 09:43
@matamegger Please check below steps
1. Download content with multiple subtitles
2. Remove particular content.
3. Once again download that content observe progress start 67% onwards.

Expected Result:  Downloading progress should be started at 0%.

Please check early as possible we are stuck.

**Closed** 2021-01-07 14:51 UTC
