### ISSUE TITLE
Unable to play dash/mpd with clear key

### ISSUE THREAD

**Issue by abhishekvuclip** [bitmovin/bitmovin-player-android-samples#63] opened 2020-02-23 19:14 UTC
How can I play dash format with clear key ?
The basic dash sample does not seem to have clear key dash url but a simple one, when i try to play the clear key dash/mpd url, it only shows subtitle but there is no video/audio.

At the same time if I play HLS/m3u8, it plays fine.

**Comment by matamegger** [comment] 2020-02-25 11:54
Duplicate of https://github.com/bitmovin/bitmovin-player-android-samples/issues/62

**Closed by matamegger** 2020-02-25 11:54 UTC
Labels: duplicate
